### ISSUE TITLE
Can't open pdf file in android.

### ISSUE THREAD

**Issue by SuperBinlin** [pwlin/cordova-plugin-file-opener2#102]
Below is my code
```
const fileTransfer = new Transfer();

fileTransfer.download(url, cordova.file.dataDirectory +'{id}.pdf').then((entry) => 
    {
       FileOpener.open(entry.toURL(), "application/pdf").then((res)=>{
         console.log("SUCCESS")
       }, (error)=>{
         console.log("ERROR")
       });
    }, (error) => {
        alert(error+'!@#$ERROR')
        // handle error
    });
```

**ios is normal but android is error.**

Error info:
```
E/chromium: [ERROR:gles2_cmd_decoder.cc(2210)] [GroupMarkerNotSet(crbug.com/242999)!:A05E2E29917C0000]GL ERROR :GL_INVALID_OPERATION : BackFramebuffer::Create: <- error from previous GL command
E/PluginManager: Uncaught exception from plugin
                 java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.microport.saapp/files/18.pdf
                     at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:711)
                     at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
                     at io.github.pwlin.cordova.plugins.fileopener2.FileOpener2._open(FileOpener2.java:104)
                     at io.github.pwlin.cordova.plugins.fileopener2.FileOpener2.execute(FileOpener2.java:61)
                     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
                     at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
                     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
                     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
                     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
                     at android.os.Handler.dispatchMessage(Handler.java:102)
                     at android.os.Looper.loop(Looper.java:154)
                     at android.os.HandlerThread.run(HandlerThread.java:61)
E/EGL_emulation: tid 4775: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
```

Can give any advice？

**Comment by liangwenzhong** [comment]
+1

**Comment by SuperBinlin** [comment]
@liangwenzhong  
Finally, I chose to use InAppBrowser and pdf.js, but the performance of Android is generally

**Comment by souly1** [comment]
+1

**Comment by pwlin** [comment]
@souly1 can you please send me a pull request for your changes so I can merge them into master branch?

**Comment by pwlin** [comment]
Thanks again for your PR. I bumped the version to 2.0.9 and push everything back to `npm`. Please upgrade!

**Comment by souly1** [comment]
Hi @pwlin , the small fix I've sent covers only files in the cached dir., so if you'll get more complaints, probably need to do something similar to the other folders...

Thanks

**Comment by pwlin** [comment]
Hi @souly1 Is there a list of which pre-defined folder exits? I can add them all to the `opener_path.xml` file

**Comment by souly1** [comment]
I took the cache folder from https://developer.android.com/reference/android/support/v4/content/FileProvider.html

**Comment by pwlin** [comment]
ok great. I'll read on that page. Thank you very much.

**Comment by souly1** [comment]
No Prob. 
thanks for the great plugin! :)

**Comment by pwlin** [comment]
You're welcome. Glad it's useful to you!
