### ISSUE TITLE
Failed to find configured root that contains "filepath"

### ISSUE THREAD

**Issue by mac89** [pwlin/cordova-plugin-file-opener2#98]
On Android 6.0.1 trying to open a file (/data/data/com.dualinventive.holdingbv/files/files/DI/Downloads/login_agreement.pdf) results in the following error message:

`E/PluginManager: Uncaught exception from plugin
                                                                            java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.dualinventive.holdingbv/files/files/DI/Downloads/login_agreement.pdf
                                                                                at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:711)
                                                                                at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
                                                                                at io.github.pwlin.cordova.plugins.fileopener2.FileOpener2._open(FileOpener2.java:104)
                                                                                at io.github.pwlin.cordova.plugins.fileopener2.FileOpener2.execute(FileOpener2.java:61)
                                                                                at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
                                                                                at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
                                                                                at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
                                                                                at org.crosswalk.engine.XWalkExposedJsApi.exec(XWalkExposedJsApi.java:40)
                                                                                at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                                at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:158)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
`

The solution to this is to add the appropriate directories in the provider paths xml file as demonstrated here:
https://developer.android.com/reference/android/support/v4/content/FileProvider.html

This needs to be either documented and/or an entry for each <paths> element needs to be added.

**Comment by pwlin** [comment]
Can you please send me a pull request with your solution? I'll be happy to merge it.

**Comment by liangwenzhong** [comment]
any solution?

**Comment by pwlin** [comment]
I have added some extra paths to `opener_paths.xml` file. Can you please update to latest version and test if you still have issues?

**Comment by idotools-joe** [comment]
i have updated to the latest version, but  this issue still unsolved

**Comment by pwlin** [comment]
@idotools-joe  can you please post your JavaScript code? Where is the location of the file you are trying to open?

**Comment by luckylooke** [comment]
It seems that I am facing the same problem
FileEntry: 
```
isFile: true, isDirectory: false, name: "montages.json", fullPath: "/montages.json", filesystem: FileSystem…}
...
nativeURL:"file:///data/user/0/com.xxx/cache/montages.json"
```
I am using nativeURL as path input for file=opener plugin
```
cordova.plugins.fileOpener2.open(
		fileEntry.nativeURL,
		'application/json',
		{
			success: () => console.log('file ' + fileEntry.name + ' opened successfully'),
			error: e => this.errors = this.util.apiErrors( e )
		}
);
```

**Comment by luckylooke** [comment]
just tried change dir to dataDirectory instead of cacheDirectory and it works... any hint here? Thanks :)

**Comment by pwlin** [comment]
Look in `/src/android/res/xml/opener_paths.xml`

Change 

    <cache-path name="cached_files" path="." />
    <external-cache-path name="cached_files" path="." />

to

    <cache-path name="cache" path="." />
    <external-cache-path name="cache" path="." />

Does that fix the problem?

**Comment by VittorioMobimentum** [comment]
Hello, I'm facing the same problem and no, @pwlin change doesn't work.
The path is always changed from `fil:///data/user/0/id.my.application/cache` to `/data/data/id.my.application/cache`.
Even if I try to give the right path (not the URL), it will be changed to the wrong one.

**Comment by Takkuz** [comment]
Hello, I'm facing the same problem and no, @pwlin change doesn't work.
The path is always changed from fil:///data/user/0/id.my.application/cache to /data/data/id.my.application/cache.
Even if I try to give the right path (not the URL), it will be changed to the wrong one.
I'm using the 2.0.19 version.

**Comment by evergreen-lee-campbell** [comment]
It looks like you committed your change to `opener_paths.xml` without increasing your version number. As such, the plugin, when added through `cordova plugin add` doesn't include the change, as it's the original 2.0.19 tag/fork (or whatever Cordova does). Could you increase your version number so that this fix replicates through?

**Comment by git1998** [comment]
@pwlin  thanks....snippets worked.
